### ISSUE TITLE
RuntimeException: Failed to initialise display event receiver.

### ISSUE THREAD

**Issue by kalallokesh** [leinardi/FloatingActionButtonSpeedDial#116]
Any idea why this is happening?
Happening on android 7 & 8

```Gradle
Caused by java.lang.RuntimeException: Failed to initialize display event receiver.  status=-19
       at android.view.DisplayEventReceiver.nativeInit(DisplayEventReceiver.java)
       at android.view.DisplayEventReceiver.(DisplayEventReceiver.java:92)
       at android.view.Choreographer$FrameDisplayEventReceiver.(Choreographer.java:845)
       at android.view.Choreographer.(Choreographer.java:225)
       at android.view.Choreographer.(Unknown Source)
       at android.view.Choreographer$1.initialValue(Choreographer.java:108)
       at android.view.Choreographer$1.initialValue(Choreographer.java:102)
       at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
       at java.lang.ThreadLocal.get(ThreadLocal.java:170)
       at android.view.Choreographer.getInstance(Choreographer.java:251)
       at android.animation.AnimationHandler$MyFrameCallbackProvider.(AnimationHandler.java:244)
       at android.animation.AnimationHandler$MyFrameCallbackProvider.(Unknown Source)
       at android.animation.AnimationHandler.getProvider(AnimationHandler.java:85)
       at android.animation.AnimationHandler.addAnimationFrameCallback(AnimationHandler.java:95)
       at android.animation.ValueAnimator.addAnimationCallback(ValueAnimator.java:1486)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1035)
       at android.animation.ValueAnimator.start(ValueAnimator.java:1065)
       at android.view.ViewPropertyAnimator.startAnimation(ViewPropertyAnimator.java:904)
       at android.view.ViewPropertyAnimator.start(ViewPropertyAnimator.java:416)
       at android.support.v4.view.ViewPropertyAnimatorCompat.start(SourceFile:644)
       at com.leinardi.android.speeddial.UiUtils.rotateBackward(SourceFile:223)
       at com.leinardi.android.speeddial.SpeedDialView.updateMainFabDrawable(SourceFile:773)
       at com.leinardi.android.speeddial.SpeedDialView.setMainFabOpenedDrawable(SourceFile:572)
       at com.leinardi.android.speeddial.SpeedDialView.setMainFabAnimationRotateAngle(SourceFile:556)
       at com.bsb.hike.ui.HomeActivity.setUpFab(SourceFile:1115)
```

**Comment by leinardi** [comment]
Are you able to reproduce this issue using the [Sample app](https://github.com/leinardi/FloatingActionButtonSpeedDial/tree/master/sample)?

**Comment by kalallokesh** [comment]
@leinardi don't have repro for this but  got 300 crashes on Fabric
